import React,{useState,useRef,useEffect} from 'react';
import ModuleSource from './ModuleSource';
import AgentWorkflowCanvas from './AgentWorkflowCanvas';
const redisBase='apps/api/src/platform/redis/';
const redisEntries=[
 {group:'Dashboard',name:'dashboard:{organizationId}:{version}',tag:'String · JSON · TTL 30s',rows:[['total / open / inProgress / completed','number'],['computedAt','string · ISO timestamp']],facts:[['Reader / writer','GetDashboard.execute'],['Cache miss','Read organization-scoped PostgreSQL statistics; cache for 30 seconds.'],['Invalidation','A new generation token changes the key used by subsequent readers; older keys expire.'],['Redis unavailable','Read PostgreSQL directly.'],['Permission scope','Organization-wide statistics; organizationId is part of the key.']],source:'apps/api/src/modules/dashboard/queries/get-dashboard.ts'},
 {group:'Dashboard',name:'dashboard-version:{organizationId}',tag:'String · UUID · no TTL',rows:[['value','string · random UUID']],facts:[['Reader','RedisService.generation'],['Initial value','SET randomUUID NX, then GET'],['Writer','RedisService.invalidate replaces the token after business changes.'],['Expiration','No expiry configured.'],['Purpose','Prevents an old in-flight query from repopulating the current cache generation.']],source:redisBase+'redis.service.ts'},
 {group:'Realtime',name:'fieldwork:changes',tag:'Pub/Sub channel · transient',rows:[['organizationId','string'],['kind','string · ASSIGNMENT_UPDATED / ASSIGNMENT_CREATED / COMMENT_ADDED'],['entityId','string']],facts:[['Publisher','PubsubService.changed after business commit; invalidates dashboard cache first.'],['Subscriber','API instances subscribe and forward to workspace:<organizationId>.'],['Browser delivery','workspaceChanged GraphQL subscription exposes kind and entityId.'],['Client reaction','Schedule an authorized data refresh.'],['Retention','No history or replay. READY after subscribing lets clients refresh after reconnect.']],source:redisBase+'pubsub.service.ts'},
];
const steps=[
 {name:'Load context',kind:'Tool',input:'projectId: string; request: string',output:'context: ProjectContext',text:'Call an organization-scoped context API using trusted actor identity. The model cannot supply or override organizationId.'},
 {name:'Draft plan',kind:'Model',input:'context: ProjectContext; request: string',output:'proposal: AssignmentDraft[]',text:'Prompt: propose actionable assignments using only the permitted project context. Return typed JSON. Example settings: temperature 0.2, output limit 2,000 tokens; model selected by deployment configuration.'},
 {name:'Validate',kind:'Code',input:'proposal: unknown; attempt: number',output:'valid: boolean; errors: string[]',text:'Validate titles, allowed priorities, project and assignee references. Invalid output retries Draft plan up to 2 times; then ends Failed.'},
 {name:'Approve',kind:'Interrupt',input:'proposal: AssignmentDraft[]; proposalVersion: string',output:'decision: approve | revise | reject',text:'LangGraph interrupt persists the pending proposal. Resume with Command({resume: decision}) and the same thread_id. Verify organization, approver and proposal version on the server. Reject ends Cancelled; revise returns to Draft plan.'},
 {name:'Execute tools',kind:'Business API',input:'approved proposal; trusted actor context',output:'results: ActionResult[]',text:'Call createAssignment for each approved item. NestJS rechecks policies and commits assignment + activity per item. Proposed idempotency keys runId:itemId prevent duplicate writes; this requires API support before deployment. A batch is not one atomic transaction.'},
 {name:'Summarize',kind:'Result',input:'results: ActionResult[]',output:'summary: string; run status',text:'Report actual committed IDs and per-item failures. Completed means all succeeded; partial failure is recorded explicitly. No invented success when a tool is denied.'},
];
const tools=[
 {name:'loadProjectContext',input:'{ projectId: string }',output:'{ project: ProjectSummary; members: Member[]; assignments: AssignmentSummary[] }',text:'Proposed read adapter. Fetch only permitted records through business APIs; actor and organization are injected by the service.'},
 {name:'createAssignment',input:'CreateAssignmentInput + proposed idempotencyKey',output:'Assignment | typed error',text:'Uses the existing createAssignment business operation. AssignmentPolicy.canCreate and canManage checks stay in NestJS. The idempotency contract is a proposed addition, not implemented by the current API.'},
];
const apis=[
 ['POST /runs','{ projectId: string; request: string }','{ runId: string; status: "queued" }','Authorize project access, create an organization-scoped run, enqueue durable execution.'],
 ['GET /runs/:id','runId','RunStatus + proposal + results','Enforce run ownership/organization on each read.'],
 ['POST /runs/:id/resume','{ proposalVersion: string; decision: "approve" | "revise" | "reject" }','RunStatus','Recheck approval policy and exact proposal version before resume.'],
 ['POST /runs/:id/cancel','runId','RunStatus','Cooperative cancellation stops future work; committed changes are not rolled back.'],
];
export default function InfrastructureExample({type,view,onChange}){
 const [tab,setTab]=useState('Workflows'),[detail,setDetail]=useState(null),[demo,setDemo]=useState('idle');
 const modal=useRef(null);
 useEffect(()=>{if(detail&&modal.current){if(!modal.current.open)modal.current.showModal();modal.current.scrollTop=0;}},[detail]);
 const show=(title,body)=>setDetail({title,body});
 const grid=(headers,rows)=><div className="table-scroll"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}><code>{c}</code></td>)}</tr>)}</tbody></table></div>;
 const showStep=s=>show(s.name,<><small>{s.kind} · proposed workflow node</small>{grid(['Input','Output'],[[s.input,s.output]])}<p>{s.text}</p><p className="muted">Suggested file: apps/agent/src/workflows/assignment-planner/{s.name.toLowerCase().replaceAll(' ','-')}.ts (not implemented)</p></>);
 return <section className="next-page infra-example">
  <div className="next-summary"><div><small>{type==='REDIS'?'REDIS · CURRENT CODE':'AGENT SERVICE · EXAMPLE DESIGN'}</small><h2>{type==='REDIS'?'Keys & channels':'Assignment planner'}</h2><p>{type==='REDIS'?'Documented key patterns and message contracts; no live Redis values are read.':'NestJS + LangGraph JS · interactive design example, not a running agent service.'}</p></div></div>
  {type==='REDIS'?['Dashboard','Realtime'].map(group=><details className="db-domain" key={group}><summary className="db-domain-heading">{group} · {redisEntries.filter(e=>e.group===group).length}</summary><div className="db-tables">{redisEntries.filter(e=>e.group===group).map(e=><article className="db-table" key={e.name}><div className="db-table-body"><h3>{e.name}</h3><p>{e.tag}</p><button onClick={()=>show(e.name,<>{grid(['Field','Type'],e.rows)}{grid(['Property','Behavior'],e.facts)}<ModuleSource path={e.source}/></>)}>Fields & behavior ↗</button></div></article>)}</div></details>):<>
   <nav className="next-tabs" aria-label="Agent views">{[['Workflows',1],['Tools',2],['Module API',4]].map(([label,n])=><button key={label} className={tab===label?'active':''} onClick={()=>setTab(label)}>{label} · {n}</button>)}</nav>
   {tab==='Workflows'&&<>
    <div className="uml-actions"><button onClick={()=>show('Workflow state',grid(['Field','Type'],[['runId / projectId','string'],['request','string'],['context','ProjectContext'],['proposal','AssignmentDraft[]'],['proposalVersion','string'],['attempt','number'],['approval','pending | approved | rejected'],['results','ActionResult[]'],['status','queued | running | awaiting_approval | completed | partial_failure | failed | cancelled']]))}>State ↗</button><button onClick={()=>show('Persistence & limits',<><p>Proposed: durable PostgreSQL checkpointer with an authorized run mapped to a LangGraph thread_id. Thread IDs do not grant access.</p><p>Keep actor/organization context trusted and separate from model output. Persist run status, graph version and proposal version.</p><p>Example limits: 2 validation retries, 20 graph steps, 120 seconds active execution. Approval wait has a separate expiry. Cancellation and budgets must be enforced by the runner.</p><p>Use a durable job runner; Redis Pub/Sub is only suitable for transient progress updates.</p></>)}>Persistence & limits ↗</button></div>
    <AgentWorkflowCanvas steps={steps} showStep={showStep} show={show} config={view?.agentCanvas} onChange={agentCanvas=>onChange?.({agentCanvas})}/>
    <section className="uml-class"><header><h3>Try an illustrative run</h3><p>Sample request: “Plan onboarding work for the workspace.” This simulation makes no model or API calls.</p></header><footer><p role="status">{demo==='idle'?'Ready':demo==='approval'?'Awaiting approval · proposal: “Prepare onboarding checklist”':demo==='done'?'Completed · simulated assignment example-001':demo==='cancelled'?'Cancelled · no actions executed':'Revision requested · generate another proposal'}</p><div className="uml-actions"><button onClick={()=>setDemo('approval')}>{demo==='idle'?'Start example':'Restart example'}</button>{demo==='approval'&&<><button onClick={()=>setDemo('done')}>Approve</button><button onClick={()=>setDemo('revision')}>Request revision</button><button onClick={()=>setDemo('cancelled')}>Reject</button></>}{demo==='revision'&&<button onClick={()=>setDemo('approval')}>Show revised proposal</button>}</div></footer></section>
    <p><a href="https://docs.langchain.com/oss/javascript/langgraph/interrupts" target="_blank" rel="noreferrer">LangGraph interrupts documentation ↗</a></p>
   </>}
   {tab==='Tools'&&<div className="db-tables">{tools.map(t=><article className="uml-class" key={t.name}><header><h3>{t.name}</h3></header><footer>{grid(['Input','Result'],[[t.input,t.output]])}<p>{t.text}</p><button onClick={()=>show(t.name,<><p>{t.text}</p>{grid(['Input','Result'],[[t.input,t.output]])}</>)}>Tool contract ↗</button></footer></article>)}</div>}
   {tab==='Module API'&&<section className="uml-class"><header><h3>Proposed run API</h3><p>All routes require authenticated, organization-scoped access. These endpoints are not deployed.</p></header>{grid(['Endpoint','Request','Response','Behavior'],apis)}</section>}
  </>}
  {detail&&<dialog ref={modal} className="uml-detail uml-modal" aria-label={detail.title} onCancel={()=>setDetail(null)}><header><h3>{detail.title}</h3><button aria-label="Close detail" onClick={()=>setDetail(null)}>×</button></header>{detail.body}</dialog>}
 </section>;
}
