const obj = (id, kind, name, description, extra = {}) => ({
  id,
  kind,
  name,
  description,
  ...extra,
});
const view = (id, name, template, ids) => ({
  id,
  name,
  template,
  objectIds: ids,
  positions: Object.fromEntries(
    ids.map((id, i) => [id, { x: (i % 3) * 350, y: Math.floor(i / 3) * 270 }]),
  ),
});
export const seed = {
  version: 1,
  name: "Fieldwork",
  objects: [
    obj(
      "member",
      "person",
      "Workspace member",
      "Plans projects, completes assignments, and discusses work.",
    ),
    obj(
      "fieldwork",
      "system",
      "Fieldwork",
      "A team workspace for projects, assignments, and activity.",
      { drillTo: "containers" },
    ),
    obj(
      "sentry",
      "external",
      "Sentry",
      "Optional error reporting. Secrets and request bodies are excluded.",
    ),
    obj(
      "web",
      "application",
      "Web application",
      "Routes and feature components. UI capabilities come from the server.",
      { technology: "Next.js · React", drillTo: "frontend" },
    ),
    obj(
      "api",
      "service",
      "GraphQL API",
      "Organization-scoped queries and use-cases enforce authorization.",
      { technology: "NestJS · GraphQL", drillTo: "components" },
    ),
    obj(
      "postgres",
      "database",
      "PostgreSQL",
      "Business records and activity are written atomically.",
      { technology: "Prisma", drillTo: "data" },
    ),
    obj(
      "redis",
      "database",
      "Redis",
      "Optional read cache; transient notifications after commit.",
      { technology: "Cache · Pub/Sub" },
    ),
    obj(
      "resolver",
      "component",
      "Assignments resolver",
      "Validates mutation input and delegates to use-cases.",
      { technology: "GraphQL" },
    ),
    obj(
      "usecase",
      "use-case",
      "Change assignment status",
      "Loads a scoped record, checks permissions and state, writes atomically.",
      { drillTo: "process" },
    ),
    obj(
      "policy",
      "policy",
      "Assignment policy",
      "Record-level authorization. Never imports guards.",
    ),
    obj(
      "rules",
      "component",
      "Assignment rules",
      "Validates business state transitions.",
    ),
    obj(
      "query",
      "query",
      "List assignments",
      "Reads directly through Prisma with organization and permission scope.",
    ),
    obj(
      "capabilities",
      "component",
      "Capability resolver",
      "Derives canComplete and the reason from policies and rules.",
    ),
    obj(
      "project",
      "entity",
      "Project",
      "Organization-owned workspace project.",
      {
        fields:
          "id: String [PK]\norganizationId: String\nname: String\ndescription: String\ncolor: String",
      },
    ),
    obj(
      "assignment",
      "entity",
      "Assignment",
      "Work item scoped to an organization.",
      {
        fields:
          "id: String [PK]\norganizationId: String\nprojectId: String [FK]\ntitle: String\nstatus: String\nassigneeId: String",
      },
    ),
    obj(
      "comment",
      "entity",
      "Comment",
      "Read access is scoped through its assignment.",
      {
        fields:
          "id: String [PK]\nassignmentId: String [FK]\nauthorId: String\nbody: String",
      },
    ),
    obj(
      "activity",
      "entity",
      "Activity",
      "Activity record written with business changes.",
      {
        fields:
          "id: String [PK]\norganizationId: String\nactorName: String\nmessage: String\ncreatedAt: DateTime",
      },
    ),
    obj(
      "page",
      "component",
      "Workspace page",
      "Assembles the workspace feature.",
    ),
    obj(
      "workspace",
      "component",
      "Workspace",
      "Coordinates queries and refetches on notifications.",
    ),
    obj(
      "detail",
      "component",
      "Assignment detail",
      "Renders the selected assignment and available actions.",
    ),
    obj(
      "complete",
      "component",
      "Complete action",
      "Uses server canComplete; server rechecks mutation authorization.",
      { drillTo: "process" },
    ),
    obj("start", "event", "Status change requested", "GraphQL mutation input."),
    obj(
      "load",
      "task",
      "Load scoped assignment",
      "Look up the record inside the actor’s organization.",
    ),
    obj(
      "check",
      "gateway",
      "Allowed?",
      "Policy and domain rules must both allow the change.",
    ),
    obj(
      "reject",
      "event",
      "Reject request",
      "Return an authorization or state error.",
    ),
    obj(
      "transaction",
      "task",
      "Write atomically",
      "Update assignment and append activity in one PostgreSQL transaction.",
      { drillTo: "data" },
    ),
    obj(
      "notify",
      "task",
      "After commit",
      "Invalidate dashboard cache and publish a transient notification.",
    ),
    obj("done", "event", "Return result", "Clients refetch authorized data."),
  ],
  relations: [
    ["member", "fieldwork", "Uses"],
    ["fieldwork", "sentry", "Reports unexpected errors"],
    ["web", "api", "GraphQL / WebSocket"],
    ["api", "postgres", "Prisma reads & transactions"],
    ["api", "redis", "Cache & Pub/Sub"],
    ["api", "sentry", "Reports errors"],
    ["resolver", "usecase", "Delegates"],
    ["usecase", "policy", "Authorizes"],
    ["usecase", "rules", "Validates state"],
    ["capabilities", "policy", "Derives permissions"],
    ["capabilities", "rules", "Checks state"],
    ["resolver", "query", "Queries"],
    ["project", "assignment", "1 → many"],
    ["assignment", "comment", "1 → many"],
    ["page", "workspace", "Renders"],
    ["workspace", "detail", "Renders"],
    ["detail", "complete", "Renders"],
    ["complete", "capabilities", "Uses canComplete"],
    ["start", "load", "Request"],
    ["load", "check", "Scoped record"],
    ["check", "transaction", "Yes"],
    ["check", "reject", "No"],
    ["transaction", "notify", "Commit"],
    ["notify", "done", "Respond"],
  ].map(([source, target, label], i) => ({
    id: `r${i}`,
    source,
    target,
    label,
  })),
  views: [
    view("context", "System context", "C1", ["member", "fieldwork", "sentry"]),
    view("containers", "Fieldwork containers", "C2", [
      "web",
      "api",
      "postgres",
      "redis",
      "sentry",
    ]),
    view("components", "API components", "C3", [
      "resolver",
      "usecase",
      "policy",
      "rules",
      "query",
      "capabilities",
    ]),
    view("frontend", "Frontend components", "C3", [
      "page",
      "workspace",
      "detail",
      "complete",
      "capabilities",
    ]),
    view("data", "Workspace data", "ERD", [
      "project",
      "assignment",
      "comment",
      "activity",
    ]),
    view("process", "Change assignment status", "BPMN", [
      "start",
      "load",
      "check",
      "transaction",
      "notify",
      "done",
      "reject",
    ]),
  ],
};
