import React,{useState,useEffect,useRef} from 'react';

function SourceLink({source}){return source?.url?.startsWith('https://github.com/')?<a className="uml-link" href={source.url} target="_blank" rel="noreferrer">Source file ↗</a>:null;}
export default function SourceModule({spec,schema,onNavigate}){
 const [tab,setTab]=useState(spec.domains.length?'domain':'api'),[query,setQuery]=useState(''),[selected,setSelected]=useState(null);
 const dialog=useRef(null);
 useEffect(()=>{if(selected&&dialog.current&&!dialog.current.open)dialog.current.showModal();if(dialog.current)dialog.current.scrollTop=0;},[selected]);
 const open=(type,item)=>setSelected({type,item});
 const link=(type,item,label)=><button className="uml-link" onClick={()=>open(type,item)}>{label} ↗</button>;
 const policy=id=>spec.policies.find(p=>p.id===id);
 const policyLinks=ids=>ids.map(id=>policy(id)&&<React.Fragment key={id}>{link('policy',policy(id),policy(id).name)} </React.Fragment>);
 const matches=item=>!query||JSON.stringify(item).toLowerCase().includes(query.toLowerCase());
 const mutations=domain=>spec.operations.filter(o=>o.owner===domain&&!['GET','Query'].includes(o.kind));
 function fields(table){return <div className="table-scroll"><table><thead><tr><th>Attribute</th><th>Type</th><th>Explore</th></tr></thead><tbody>{table.fields.map(field=><tr key={field.name}><td><code>{field.name}</code></td><td><code>{field.type}</code></td><td>{field.capabilities?link('capabilities',field.capabilities,'Permissions'):field.enumValues?link('enum',{name:field.type,values:field.enumValues},`Options · ${field.enumValues.length}`):field.reference||field.target?link('table',schema?.tables.find(t=>t.name===(field.reference?.table||field.target)),field.reference?`${field.reference.table}.${field.reference.field}`:field.target):'—'}</td></tr>)}</tbody></table></div>;}
 function operations(items){return <div className="table-scroll"><table><thead><tr><th>Action</th><th>Input → result</th><th>Policy</th><th>Behavior</th></tr></thead><tbody>{items.map(operation=><tr key={operation.id}><td><code>{operation.name}</code><small>{operation.kind} {operation.endpoint!==operation.name&&operation.endpoint}</small></td><td><code>{operation.input||'No parameters'} → {operation.result}</code></td><td>{operation.policyIds.length?policyLinks(operation.policyIds):'See operation checks'}</td><td>{link('operation',operation,'Open')}</td></tr>)}</tbody></table></div>;}
 return <section className="next-page uml-view source-module">
  <div className="next-summary"><div><small>MODULE · UML</small><h2>{spec.title}</h2><p>{spec.summary}</p></div><span className="uml-badge">Source · {spec.revision.slice(0,8)}</span></div>
  <nav className="next-tabs" aria-label="Module views">{[['domain',`Domain objects · ${spec.domains.length}`],['api',`Module API · ${spec.operations.length}`],['policies',`Policies · ${spec.policies.length}`]].map(([id,label])=><button key={id} className={tab===id?'active':''} aria-pressed={tab===id} onClick={()=>{setTab(id);setQuery('');}}>{label}</button>)}</nav>
  <input aria-label="Search module documentation" placeholder="Find an object, action or policy…" value={query} onChange={e=>setQuery(e.target.value)}/>
  {tab==='domain'&&<><p className="muted">Persisted domain models from Prisma. API inputs and responses may expose different fields.</p><div className="uml-classes">{spec.domains.filter(domain=>matches(domain)||mutations(domain.name).some(matches)).map(domain=><article className="uml-class" key={domain.name}><header><small>«Domain object»</small><h3>{domain.name}</h3><div className="uml-actions">{policyLinks(domain.policyIds)}<SourceLink source={domain.source}/></div></header>{fields(domain)}{mutations(domain.name).length>0&&<section className="uml-object-actions"><h4>Actions · {mutations(domain.name).length}</h4>{operations(mutations(domain.name))}</section>}</article>)}</div>{!spec.domains.length&&<p>No domain objects owned by this module. Its operations are under Module API.</p>}</>}
  {tab==='api'&&<><p className="muted">All documented module endpoints. Object actions are also linked from their domain cards.</p><section className="uml-class">{operations(spec.operations.filter(matches))}</section>{!spec.operations.length&&<p>No public endpoints declared for this module.</p>}</>}
  {tab==='policies'&&<div className="uml-classes">{spec.policies.filter(matches).map(item=><article className="uml-class" key={item.id}><header><h3>{item.name}</h3><SourceLink source={item.source}/></header><div className="source-module-policy">{item.methods.map(method=><p key={method.name}>{link('policy',item,method.signature)}</p>)}</div></article>)}{!spec.policies.length&&<p>No standalone policy definition in this module. Inspect the operation for its identity and delegated authorization checks.</p>}</div>}
  <p className="muted">Source snapshot. Enum options describe values, not proven state transitions. Policy links reference calls found in the operation implementation.</p>
  {selected&&<dialog ref={dialog} className="uml-detail uml-modal" aria-label="Linked detail" onCancel={()=>setSelected(null)} onClick={e=>{if(e.target===e.currentTarget)setSelected(null);}}><header><div><small>LINKED DETAIL</small><h3>{selected.item?.name||'Related table'}</h3></div><button aria-label="Close class detail" onClick={()=>setSelected(null)}>×</button></header>
   {selected.type==='enum'&&<ul>{selected.item.values.map(value=><li key={value}><code>{value}</code></li>)}</ul>}
   {selected.type==='capabilities'&&<><p>Computed API fields supplied to the frontend, not persisted columns. Backend authorization still applies to each operation.</p><SourceLink source={selected.item.source}/>{fields(selected.item)}<h4>Central policy</h4>{policyLinks(selected.item.policyIds)}</>}
   {selected.type==='table'&&(selected.item?<><SourceLink source={{url:`https://github.com/zhubek/sb2/blob/${spec.revision}/backend/prisma/schema.prisma`}}/>{fields(selected.item)}<button onClick={()=>onNavigate(spec.databaseViewId)}>Open database view →</button></>:<p>Table definition is unavailable.</p>)}
   {selected.type==='policy'&&<><p>Central policy definition referenced by operations.</p><SourceLink source={selected.item.source}/>{selected.item.methods.map(method=><details key={method.name} open><summary>{method.signature}</summary><pre>{method.code}</pre></details>)}</>}
   {selected.type==='operation'&&<><dl className="uml-facts"><dt>Endpoint</dt><dd>{selected.item.kind} {selected.item.endpoint}</dd><dt>Domain</dt><dd>{selected.item.owner||'Module-wide'}</dd><dt>Input</dt><dd><code>{selected.item.input||'None'}</code></dd><dt>Result</dt><dd>{selected.item.result}</dd></dl><h4>Policy checks</h4>{policyLinks(selected.item.policyIds)}{selected.item.policyCalls.map((call,i)=><pre key={i}>{call.expression}</pre>)}{!selected.item.policyIds.length&&<p>No direct call to a documented policy was found. Review the implementation and delegated calls.</p>}<h4>Transaction boundary</h4><p>{selected.item.transaction}</p>{selected.item.dtos.map(dto=><details key={dto.name}><summary>Input · {dto.name}</summary><SourceLink source={dto.source}/><pre>{dto.code}</pre></details>)}<h4>Behavior · {selected.item.implementation.symbol}</h4><SourceLink source={selected.item.implementation}/><pre>{selected.item.code}</pre><h4>API entry</h4><SourceLink source={selected.item.source}/></>}
  </dialog>}
 </section>;
}
